name: DevSecOps Full Pipeline

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
      - master
      
permissions:
      contents: read
      issues: write
      
jobs:

#---- SAST com Semgrep ----#
  semgrep:
    name: SAST - Semgrep
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@v4
    #- run: semgrep ci
    - run: semgrep --config p/owasp-top-ten --json --output semgrep.json .

#---- SCA com Snyk ----#
  sca-snyk:
    name: Snyk with High threshold
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

#---- DAST com ZAP ----#
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://animated-fortnight-7vv7v5gqvgq9fx4qj-3000.app.github.dev/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

# --- Secrets scan com Gitleaks --- #
  secrets_gitleaks:
    name: Secret Scan - Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
